//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficMatrix2013
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SAM_CONFIG> SAM_CONFIG { get; set; }
        public DbSet<SAM_DATA_C> SAM_DATA_C { get; set; }
        public DbSet<SAM_DATA_D> SAM_DATA_D { get; set; }
        public DbSet<SAM_DATA_S> SAM_DATA_S { get; set; }
        public DbSet<SAM_GROUP> SAM_GROUP { get; set; }
        public DbSet<SAM_LOG> SAM_LOG { get; set; }
        public DbSet<SAM_PRMS> SAM_PRMS { get; set; }
        public DbSet<SAM_USER> SAM_USER { get; set; }
    }
}
