//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficMatrix2013
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAM_PRMS
    {
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string VALUE { get; set; }
    }
}
