//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficMatrix2013
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAM_DATA_S
    {
        public Nullable<System.DateTime> DT_WIN { get; set; }
        public decimal DT_UNX { get; set; }
        public string ADR_SOURCE { get; set; }
        public string ADR_TARGET { get; set; }
        public Nullable<decimal> TRF_TOTAL { get; set; }
        public Nullable<decimal> TRF_DELTA { get; set; }
    }
}
