//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficMatrix2013
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAM_GROUP
    {
        public SAM_GROUP()
        {
            this.SAM_USER = new HashSet<SAM_USER>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string DESCRIPTION { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual ICollection<SAM_USER> SAM_USER { get; set; }
    }
}
