//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficMatrix2013
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAM_LOG
    {
        public decimal ID { get; set; }
        public string DT_PERIOD1 { get; set; }
        public string DT_PERIOD2 { get; set; }
        public Nullable<decimal> DT_ELAPSED { get; set; }
        public string SAM_FILENAME { get; set; }
        public Nullable<decimal> COUNT_RAW { get; set; }
        public Nullable<decimal> COUNT_PRC { get; set; }
        public Nullable<decimal> COUNT_S { get; set; }
        public Nullable<decimal> COUNT_C { get; set; }
        public Nullable<decimal> COUNT_D { get; set; }
        public string LOG_DATETIME { get; set; }
        public string LOG_USERNAME { get; set; }
        public string LOG_FULLTEXT { get; set; }
        public string STATUS { get; set; }
    }
}
